### PR TITLE
Added privacy policy page

### LINKED ISSUE #254: Add a new page containing our club's privacy policy
### What's your idea?

The board on acmCSUF has drafted up a privacy policy document that we can convert into a new Svelte component.

### PR DESCRIPTION
**Pull request by EthanThatOneKid**
I added the privacy policy page based on the most recent version created by the acmCSUF board.

Resolves #254.
Preview: <https://acm-csuf-site-git-fix-254-ethanthatonekid.vercel.app/privacy>.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
// Intro
Change "acmCSUF's Privacy Policy" to "Our privacy policy", capitalize Discord.

// Headers
Lowercase "Collect", "Information", "Retention", "Data Rights and Choices", "Privacy Policy", and "Us" in its respective headers

On every H2, add class="headers" to change the weight of the headers to slimmer.  According to the design guidelines, bold/font weight 700 is reserved **only** for the following keywords: CSUF, Path Names, and the Color Palette

Change the font-weight for "Information you provide" and "Data we collect automatically" to 500 to adhere to the design guidelines

Do we have acmcsuf@gmail.com?

**Comment by EthanThatOneKid** [comment]
> // Intro Change "acmCSUF's Privacy Policy" to "Our privacy policy", capitalize Discord.

Done.

> // Headers Lowercase "Collect", "Information", "Retention", "Data Rights and Choices", "Privacy Policy", and "Us" in its respective headers

Done; I kept the proper capitalization in the markup, but I made the text visually lower-cased with the [`text-transform: lowercase`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) CSS property.

> On every H2, add class="headers" to change the weight of the headers to slimmer. According to the design guidelines, bold/font weight 700 is reserved **only** for the following keywords: CSUF, Path Names, and the Color Palette
> 
> Change the font-weight for "Information you provide" and "Data we collect automatically" to 500 to adhere to the design guidelines

Done and done. Is there a link you could share in reference to the design guidelines you speak of?

> Do we have [acmcsuf@gmail.com](mailto:acmcsuf@gmail.com)?

Good catch! I corrected this to acmcsufullerton@gmail.com.

I will request a re-review now. Thanks!

**Comment by ghost** [comment]
> Done; I kept the proper capitalization in the markup, but I made the text visually lower-cased with the [`text-transform: lowercase`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) CSS property.

With this, I meant rather than

### Information we Collect

Change it to

### Information we collect

The first word will always be uppercased, just like a normal sentence.

---

So with that said, all the headers should be stylized as

### Welcome to ACM!

### Information we collect

### Our use of your information

### Data retention

### Your data rights and choices

### Changes to this privacy policy

### Contacting us

**Comment by EthanThatOneKid** [comment]
> > Done; I kept the proper capitalization in the markup, but I made the text visually lower-cased with the [`text-transform: lowercase`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) CSS property.
> 
> With this, I meant rather than
> 
> ### Information we Collect
> Change it to
> 
> ### Information we collect
> The first word will always be uppercased, just like a normal sentence.

I see what you mean! Alright, I fixed that too.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
