### PR TITLE
Blog page design tweaks

### LINKED ISSUE #430: Blog logo unreadable when in dark mode
### What happened?

The README logo is unreadable in dark mode, and the borders around the articles also disappears.

Light
image
Dark
image

### PR DESCRIPTION
**Pull request by ghost**
#### CHANGELOG
- Removed shadows bc too jarring
- Re-added stroke from initial design
- Cards turn gray in dark mode

This is change #7 of my big update to prepare for next semester's codebase.

### CODE REVIEW

**Review by jaasonw — CHANGES_REQUESTED** [review]
footer is not 100vw'd properly

**Comment by jaasonw** [comment]
image

**Comment by jaasonw** [comment]
IT DOESNT WORK ON MY GALAXY FOLD

**Comment by ghost** [comment]
> IT DOESNT WORK ON MY GALAXY FOLD

imagine having a fold KEKW

**Comment by jaasonw** [comment]
https://user-images.githubusercontent.com/8981287/160302348-34e56422-df3d-4dca-83b1-ae146dff4c4f.mp4

**Review by jaasonw — CHANGES_REQUESTED** [review]
toast is not max width'd

**Comment by jaasonw** [comment]
also i cant see the blog due to https://github.com/EthanThatOneKid/acmcsuf.com/issues/407

**Review by EthanThatOneKid — APPROVED** [review]
LGTM! This seems to resolve #407.

**Comment by jaasonw** [comment]
> LGTM! This seems to resolve #407.

https://acm-csuf-site-git-mike-blog-design-tweak-ethanthatonekid.vercel.app/blog no it doesnt

image

**Review by jaasonw — CHANGES_REQUESTED** [review]
see above

**Comment by jaasonw** [comment]
@mikeploythai can you fix https://github.com/EthanThatOneKid/acmcsuf.com/issues/267 too

**Comment by ghost** [comment]
> @mikeploythai can you fix #267 too

ok

**Review by EthanThatOneKid — APPROVED** [review]

**Comment by EthanThatOneKid** [comment]
> > LGTM! This seems to resolve #407.
> 
> https://acm-csuf-site-git-mike-blog-design-tweak-ethanthatonekid.vercel.app/blog no it doesnt
> 
> image

Is this still happening on your end, @jaasonw?

**Comment by jaasonw** [comment]
it doesn't but i still want #267 fixed first

**Comment by EthanThatOneKid** [comment]
> [12:57 PM] moike: Okok go ahead and close 426, 415, 414, 413, and 406

**Comment by Angel-Armendariz** [comment]
que paso

**Pull request closed without merging**
