### PR TITLE
Refactor flexbox to grid (Issues: #136)

### LINKED ISSUE #136: Officer image sizing inconsistencies
The sizing of the ACM officer images are inconsistent; some appear smaller than others even when set to the same width and height in CSS.

### PR DESCRIPTION
**Pull request by anhduy1202**
I manage to refactor to grid but grid-template-columns: auto-fill doesn't work responsively as it should, I think this may be due to other component's style since auto-fill should auto adjust the grid columns according to the viewport width, any suggestions? I can use media query to determine number of columns easily, but I think auto-fill is a much cleaner solution, thanks!

### CODE REVIEW

**Comment by anhduy1202** [comment]
oh yeah and I think my branch is outdated so that's why the preview doesn't have one officer, but other than that, it's the responsiveness that I want to discuss

**Comment by diamondburned** [comment]
Minor comment: the code in this PR uses tabs in some places instead of spaces,
like the rest of the project.

**Comment by anhduy1202** [comment]
it looks off on mobile-view, I’ll probably fix it again

**Comment by EthanThatOneKid** [comment]
> it looks off on mobile-view, I’ll probably fix it again

Can you provide an example for where it looks off?

**Review by EthanThatOneKid — APPROVED** [review]
The biggest visual change is that the officer profiles are left-justified (opposed to being centered) as seen below.

image

Your change was executed nicely. The next steps for this PR are to update the branch from main (in GitHub Desktop: <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd>) and then to await @mikeploythai's review.

**Review by ghost — CHANGES_REQUESTED** [review]
Make the max-width of the section up to around 1150px. Nothing on the website can extend beyond the start and end of the nav bar visually, as per website design guidelines

**Comment by EthanThatOneKid** [comment]
Closed by #241.

**Pull request closed without merging**
