### PR TITLE
Add `acmcsuf.com/colors`

### PR DESCRIPTION
**Pull request by EthanThatOneKid**
Welcome to documentation generated straight from the `global.css` file.

This page helps acmcsuf.com contributors find just the color they are looking for.

### Screenshot

image

### Related

- #542

### CODE REVIEW

**Review by k4rni — CHANGES_REQUESTED** [review]
Is the page `acmcsuf.com/colors`? It keeps redirecting to `acmcsuf.com/c`.

**Comment by k4rni** [comment]
The shortlink is actually `acmcsuf.com/_colors'.

Can you spread the colors so that they don't wrap and fit all in one line? Also add a hover effect as well for copying the hex.

**Review by k4rni — APPROVED** [review]

**Review by k4rni — CHANGES_REQUESTED** [review]
Refer to https://github.com/EthanThatOneKid/acmcsuf.com/pull/1033#issuecomment-1998559574

**Comment by EthanThatOneKid** [comment]
> Is the page `acmcsuf.com/colors`? It keeps redirecting to `acmcsuf.com/c`.

Resolved in #1044.

**Comment by EthanThatOneKid** [comment]
> Can you spread the colors so that they don't wrap and fit all in one line? Also add a hover effect as well for copying the hex.

Addressed in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/1033/commits/d0c877d5dd5c6f090ad3786ff831538328596329>.

**Review by k4rni — APPROVED** [review]

**Pull request merged**
