### PR TITLE
Add `/boardify` page to crop board member images

### LINKED ISSUE #546: Boardify: Board member picture frame generator
### What's your idea?

@jaasonw suggested that we have a dedicated web application to facilitate the creation of board member pictures that are used on `/about`.

Context:
6:06 PM]jasonw: nah, like imagine like a web app
[6:06 PM]jasonw: u upload a headshot
[6:06 PM]jasonw: and then u move the picture around to fit
[6:06 PM]jasonw: and then when u hit export, it's in the correct size and format

Related: #348

### PR DESCRIPTION
**Pull request by EthanThatOneKid**
Resolves #546!

### CODE REVIEW

**Comment by caretcakejake** [comment]
I like the new feature!
- Mayhaps it would be good to add a min width and height to the crop box I got it really tiny on accident and it was hard to drag out again
- Also copy to clipboard button for the future discord command would be awesome

**Comment by EthanThatOneKid** [comment]
> Mayhaps it would be good to add a min width and height to the crop box I got it really tiny on accident and it was hard to drag out again

@barrotbake thank you for the code review! When you have a chance, could you clarify the specific accident you are referring to?

**Comment by caretcakejake** [comment]
@EthanThatOneKid I think I got it smaller last time but the frame height and width was difficult to drag back out again. So maybe a minimum height and width for the frame may be helpful.

image

**Review by k4rni — APPROVED** [review]
Perfect! I'm ready to use it. Thank you for all your hard work.

**Review by anguzz — COMMENTED** [review]
nice!

**Pull request merged**
