### PR TITLE
Update board-member.svelte

### PR DESCRIPTION
**Pull request by JOwen-ster**
please merge it guys

### CODE REVIEW

**Comment by k4rni** [comment]
no ❤️

**Comment by NateGries1** [comment]
nice code bro

**Comment by k4rni** [comment]
omg it's big nate

**Review by NateGries1 — APPROVED** [review]
looks perfect. Good to go

**Comment by 26samaahmed** [comment]
wow

**Comment by JOwen-ster** [comment]
guys it needs to be merged very important security vul.

**Comment by EthanThatOneKid** [comment]
After careful consideration, No

**Comment by k4rni** [comment]
Thank you for your contributions.

**Pull request closed without merging**
