### PR TITLE
Index page adjustments

### LINKED ISSUE #347: Button hover effect
### What happened?

i recently heard that the plan is to change text color on button hover rather than background-color of the button on button hover. i disagree with this because it's not a good UX choice due to the colors we use.

as it currently stands, the colors we use in our design language is bad for accessibility on dark backgrounds (one of the reasons why I strayed away from dark mode at the early stages of the website) due to how saturated the colors are. relating to this, acmBlue does not look good on acmDark because both colors are too dark. this is why I designed the buttons to change the background color to acmBlue on hover.

i recommend that for buttons, background-color change should be the hover effect.

### PR DESCRIPTION
**Pull request by ghost**
#### CHANGELOG
- Changed font macros for paragraphs from `size-xs` to `size-sm`
- Breakpoint is set to 900px
- Images use `clamp()` to scale dynamically
- `AcmButton` re-written to use `--button-bg` and `--button-hover` for different styles in light/dark themes
- Modified wording in some paragraphs

This is change #3 of my big update to prepare for next semester's codebase.

Mods to AcmButton (and AcmSelect in another PR) fixes #347.

### CODE REVIEW

**Comment by jaasonw** [comment]
it doesnt work on my iphone 5
https://user-images.githubusercontent.com/8981287/160266976-4e9169e4-efff-479b-ba23-2c4b3726e5b0.mp4

**Comment by jaasonw** [comment]
it doesnt work on my iphone 5 / se 
https://user-images.githubusercontent.com/8981287/160266985-dcdad6be-a2fa-43e2-8f03-8ee642b9ef40.mp4

**Review by jaasonw — CHANGES_REQUESTED** [review]
it doesnt work on my iphone se, see next comment

**Comment by jaasonw** [comment]
https://user-images.githubusercontent.com/8981287/160267051-136aed94-e8eb-42c3-a073-564baf946249.mp4

**Comment by jaasonw** [comment]
image
it doesnt when i flip my iphone sideways also

**Comment by ghost** [comment]
> asdff.mp4

https://user-images.githubusercontent.com/54593375/160267245-f0d07220-9f7a-4eab-9b71-22a39244a9f7.mp4

Works fine for iPhone SE. I had this issue a lot when emulating but all I had to do was switch it to a different viewport width, close out of dev options, and then open up dev options again and change the viewport back to SE.

**Comment by ghost** [comment]
> image it doesnt when i flip my iphone sideways also

god just don't flip ur phone weirdchamp

anyway yeah i can fix this in a diff pr lol

**Comment by ghost** [comment]
> > image it doesnt when i flip my iphone sideways also
> 
> god just don't flip ur phone weirdchamp
> 
> anyway yeah i can fix this in a diff pr lol

Fixed in #401

**Review by jaasonw — CHANGES_REQUESTED** [review]
i found another issue on my iphone

**Comment by jaasonw** [comment]
https://user-images.githubusercontent.com/8981287/160267477-0c3db6c0-1941-4760-96ef-10aeab2aa31c.mp4

**Comment by ghost** [comment]
> 2022-03-26.22-01-21.mp4

That's been fixed with #403. QA test #406

**Comment by jaasonw** [comment]
changes merged in https://github.com/EthanThatOneKid/acmcsuf.com/pull/405 and https://github.com/EthanThatOneKid/acmcsuf.com/pull/401

**Pull request closed without merging**
