### PR TITLE
Feat/1098

### LINKED ISSUE #1098: 100 Days of Design Gallery Page
### What's your idea?

Since a lot of our ACM members have been working hard making the daily design challenges hosted by the Design Team, I want to show case all the amazing designs for people to easily look back on a gallery page!

### PR DESCRIPTION
**Pull request by adriancancode**
Started my initial layout for the 100 days of design gallery as per issue #1098.

### CODE REVIEW

**Comment by rhellwege** [comment]
I added the design-gallery page along with data and types for DesignGalleryEntry.

The page shows the top 10 entries to the Summer 100 Days of Design challenge with each entry's prompt, day number and designer.

screenshot-2024-12-01-21-40-05

**Comment by 26samaahmed** [comment]
@rhellwege it looks really good so far👏 I have checked to see if the page was responsive but it seems that the text is too big on mobile view. I think it's also better to have only 1 design per row on mobile view instead of 2. 

Screenshot 2024-12-01 175611


I edited the description at the top of the page and I added the page link to our sitemap so people can check it out!

Screenshot 2024-12-01 180846

**Comment by rhellwege** [comment]
@26samaahmed I added the changes so it looks better on mobile.
screenshot-2024-12-02-18-15-55

**Review by 26samaahmed — APPROVED** [review]
It looks so good I love it! It's now responsive on all devices, congrats on your first contribution to the website @rhellwege 😎

**Pull request merged**
