### PR TITLE
Delete duplicate links data file

### LINKED ISSUE #756: Duplicate links data file
### Problem

There be 2 link data files, [`src/lib/server/links/data.ts`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/c0c027598fd32852e097b9ca98de0ac99c1c6b74/src/lib/server/links/data.ts) and [`src/lib/public/links/links.json`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/c0c027598fd32852e097b9ca98de0ac99c1c6b74/src/lib/public/links/links.json).

### My reaction

THERE ARE TWO LINK FILES?!

### Solution

Delete `src/lib/server/links/data.ts` in favor of `src/lib/public/links/links.json`.

### PR DESCRIPTION
**Pull request by k4rni**
Fix #756.

### CODE REVIEW

**Review by jaasonw — APPROVED** [review]
🍛🍣🐖😶🍕♑🈹🐒🐆🦬🍕🍔🍟😮🍟🥨🥡🍤🥩🚞🍕🚃😭🧐🥙🍕🍔🚠🚆🛹🚋🚈🛴💫💨💝💌🕳️🚋🍕🥨🚡💦💕🥺🤔🐕🐎💞🏍️🏎️🍕💫😌🍕🤑💫💢💗☯️♌⛎😥😢♍😧😨🤨👉👈🈹

**Comment by k4rni** [comment]
> https://github.com/EthanThatOneKid/acmcsuf.com/issues/756#issuecomment-1472913902

@jaasonw can you take a look at this? For some reason the `student-pack` shortlink, which is supposed to link to `https://acmcsuf.com/blog/806` link, is the only one that does not work. Do you know why?

**Comment by jaasonw** [comment]
is it not bcus they're duplicated?

**Comment by EthanThatOneKid** [comment]
> is it not bcus they're duplicated?

No. We discovered a regression in the `findURL` function.

The current plan is to replace the code path that `throw`s by passing a `destinationOrigin` to use when resolving a found shortlink missing a destination origin.

However, this means `findURL` finds a URL every time which strays from the expected behavior implied by the function name.

**Comment by EthanThatOneKid** [comment]
> No. We discovered a regression in the findURL function.

The `findURL` regression has been followed up in #818.

**Comment by jaasonw** [comment]
https://docs.netlify.com/routing/redirects/ why not just do all these redirects directly in netlify

**Comment by EthanThatOneKid** [comment]
> https://docs.netlify.com/routing/redirects/ why not just do all these redirects directly in netlify

We want the feature to work no matter which provider we deploy with.

**Pull request merged**
