### PR TITLE
Change color of officer title prefixes only

### LINKED ISSUE #384: Hyperactive color replacement in officer titles
### What happened?

The officer position titles on [`acmcsuf.com/about`](https://acmcsuf.com/about) are passed through a function that adds colors to the words `Algo`, `Create`, `Dev`, and `NodeBuds` as they appear.

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/4c7a31bce9a4e83ec252946f34d467bbb83aab6f/src/lib/components/about/officer-profile.svelte#L13-L20>

The title segment being replaced is always expected to be used as a prefix separated by a space. To reflect this strictness, we could possibly use something similar to the regular expression `/Dev\s/` (do not forget to replace the space). 

### Screenshot

image

### PR DESCRIPTION
**Pull request by anguzz**
Co-Authored-By: Mohamed Habarneh <92408806+MohamedHabarneh@users.noreply.github.com>
Fixed about page coloring of paths in front of officer titles

Fixes: https://github.com/EthanThatOneKid/acmcsuf.com/issues/384

### CODE REVIEW

**Comment by jaasonw** [comment]
you should link the issue that gets fixed in your pull request like this https://github.com/EthanThatOneKid/acmcsuf.com/issues/384 as it will auto close the issue when the pull request gets merged

**Review by jaasonw — APPROVED** [review]
i see no issues with this

**Comment by jaasonw** [comment]
also ill just edit the pr comment but just a thing to remember for next time

**Comment by anguzz** [comment]
ok will do!

**Pull request merged**
