### PR TITLE
Add support for ics.acmcsuf.com

### PR DESCRIPTION
**Pull request by diamondburned**
This commit adds support for parsing ICS calendars using the ICal
standard format in addition to the existing Google Calendar API.

The new commit also contains a hard-coded array of ICS calendar links,
currently only containing ics.acmcsuf.com. In the future, more links may
be added to this.

A hard-coded array was chosen over an environment variable because
environment variables cannot express arrays as easily. That said, if
there are any private calendars, then they can be used as such:

    const KnownCalendars = [
      "public1.ics",
      "public2.ics",
      SECRET_ICS_X,
      SECRET_ICS_Y,
    ]

In the future, if ics.acmcsuf.com is proven to work well enough, the
Google Calendar API could even be completely phased out.

NOTE: It is worth pointing out that this ICS code currently *does not
support recurring events*. This is because ics.acmcsuf.com doesn't do
recurring events.

### CODE REVIEW

**Comment by diamondburned** [comment]
This PR also adds `typescript-language-server` as a `devDependency`. If you don't want this, feel free to cherry-pick the commit out and consider this PR manually merged.

**Review by EthanThatOneKid — COMMENTED** [review]
Interesting, I'll look into this soon. This seems to be a reimagining of the ICS parser [`src/lib/server/events/ical.ts`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/1b7dc5d60e8b523d65ccf52bfc9b9600c48f960e/src/lib/server/events/ical.ts) we maintained before switching to Google Calendar.

Relevant PR: https://github.com/EthanThatOneKid/acmcsuf.com/pull/696

**Comment by diamondburned** [comment]
Yes. #646 shouldn't really happen since we have the cache, but also `ics.acmcsuf.com` is much faster than Google Calendar at serving ICS and also does internal caching for this.

**Comment by diamondburned** [comment]
Closing this PR, since the team doesn't seem to be interested in merging/reviewing it.

**Comment by EthanThatOneKid** [comment]
> Closing this PR, since the team doesn't seem to be interested in merging/reviewing it.

Apologies for not getting around to posting an official review on this PR. I recall testing this PR locally a while ago and it did not seem to be ready/working.

cc @diamondburned

**Comment by diamondburned** [comment]
> it did not seem to be ready/working.

What was the error?

**Comment by EthanThatOneKid** [comment]
> What was the error?

@diamondburned, I don’t recall if there was an error. I actually remember noticing no events were showing despite having events on Discord. I also DM’d you on Discord about this in mid-October.

**Comment by diamondburned** [comment]
You should give it a try again. I think the bot might've left the server randomly, but it's back now.

I don't remember you replying to me after sending my messages about it.

**Pull request closed without merging**
