### PR TITLE
Center NodeBuds logo animation on mobile

### LINKED ISSUE #985: Center the nodebuds logo animation on mobile
### What happened?

On mobile mode, the nodebuds logo moves towards one end and back towards the center. It should be altered slightly so that the animation can look more centered.

nodebuds

### PR DESCRIPTION
**Pull request by 26samaahmed**
Fix #985 

https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/104ad2e9-cea9-4bc4-a9a6-d1edb2831694

### CODE REVIEW

**Comment by JustinStitt** [comment]
Hi, I do not notice the same issue reported in #985 for mobile -- for me, the logo is pretty darn well centered on mobile.

With that being said, I think you're on the right track with your change; as far as making this animation look better.

Could we try reducing the side-to-side movement of this animation and have it spend more time in the center?

Here's an example (sorry the gif doesn't loop perfectly):



This was created with:

```js
  .nodebuds-animation img {
    ...
    animation-timing-function: cubic-bezier(0, 0, 0, 0);
    ...
  }

  @keyframes slide {
    0% {
      left: -60px;
    }

    33% {
      left: -5px;
    }

    50% {
      left: 0;
    }

    66% {
      left: 5px;
    }

    100% {
      left: 60px;
    }
  }
```

**Comment by 26samaahmed** [comment]
Hii, I updated the animation as suggested by reducing the side to side movement. Thank you for the suggestion, it looks better now.


https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/0b60e578-7eaa-49fb-a0d1-680b9ad07ea3

**Review by JustinStitt — APPROVED** [review]

**Review by k4rni — APPROVED** [review]
This looks really clean! Nice work Sama :heart:

**Comment by k4rni** [comment]
Make sure to update the branch!

**Review by EthanThatOneKid — APPROVED** [review]

**Pull request merged**
