### PR TITLE
Fix effects links on Blog

### LINKED ISSUE #745: Blog: Hover and visit effect on links
### What's your idea?

Links inside of blog posts do not give off any effect when hovered over or visited.

### Boring screenshot

image

One link is being hovered over and one link has been visited, but you cannot tell. Hence the issue.

### References

- <https://developer.mozilla.org/en-US/docs/Web/CSS/:hover#examples>
- <https://developer.mozilla.org/en-US/docs/Web/CSS/:visited#examples>

### PR DESCRIPTION
**Pull request by nghuyhoang0204**
Hello , this is my first time make a PR so if there is anything wrong please tell me or comment 😄 
So this is my work about this issue and here is the result 

Screenshot 2023-02-15 at 14 35 13

### CODE REVIEW

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
Your changes look good in `src/routes/(site)/blog/[id]/blog-body.svelte`.

However, there are unnecessary changes in `.env.example` and `scripts/.env.example`. Please undo the changes in those files.

**Review by EthanThatOneKid — APPROVED** [review]
Looks good. Thanks for contributing, @nghuyhoang0204!

**Comment by nghuyhoang0204** [comment]
Thanks for your fast reply 😄

**Comment by k4rni** [comment]
Resolves #745.

**Pull request merged**
