### PR TITLE
make blog images responsive

### LINKED ISSUE #789: Image overflow on the blogs
### What happened?

There's no image scaling for mobile on the blog :(( [my blog](https://acmcsuf.com/blog/787) is ruined 
<picture>

</picture>

### PR DESCRIPTION
**Pull request by jaasonw**
fix #789

### CODE REVIEW

**Comment by jaasonw** [comment]
these arent gonna show in the preview i had to inspect element this in but im p sure it works

image
image

**Comment by charliettaylor** [comment]
```css
:global(img) {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}
```
is it worth it to add object-fit for fun or does it not do anything? I was running this on local and it seemed to be working too

**Comment by jaasonw** [comment]
fun has been added

**Comment by jaasonw** [comment]
i dont think it does anything though, so maybe just keep it simple?

**Review by stephaniePocci — APPROVED** [review]
Looks pog, tysm!

**Pull request merged**
