### PR TITLE
Rearranged board members

### PR DESCRIPTION
**Pull request by ghost**
As per karni's request. Final change to tiers.json

### CODE REVIEW

**Comment by jaasonw** [comment]
Can we bump historian up some ranks too

**Comment by ghost** [comment]
> Can we bump historian up some ranks too

no

**Comment by jaasonw** [comment]
> > Can we bump historian up some ranks too
> 
> no

D:<

**Comment by k4rni** [comment]
Sorry for the late response but we're nearing the end of this semester and I feel like there's no point in updating the tiers at this very moment when the entire list will be changing so I'm just gonna deny this and then we can figure it all out again next semester.

**Comment by jaasonw** [comment]
F in the chat

**Pull request closed without merging**
