### PR TITLE
rebrand 2022

### LINKED ISSUE #470: Change Paths to Teams
### What happened?

Replace all path badges with newly updated Figma assets. Descriptions must include "Chapter" and must be described as **Teams** rather than as Paths. Include new AI team.

Figma Library: https://www.figma.com/file/dHwyipuuf90ZVzFlHKS3AC/Design-Library?node-id=0%3A1 

| Outdated | Updated |
| --- | --- |
| image | image 
| image | image
| image | image

### LINKED ISSUE #509: Need AI Team Button
### What happened?

Right now there is no AI Team hyperlink button on the front page when you scroll down - only Algo, Create and Dev. We also need to add a short description for the Teams page.

### LINKED ISSUE #510: Naming Changes
### What happened?

# The site needs a few naming changes/updates
- [x] #470
- [x] #610
- [x] #611

### PR DESCRIPTION
**Pull request by jaasonw**
- change acmPath to teams
- change create to design
- add ai button
- add ai section
- revise algo wording slightly

fixes #509 #510 #470 

note: code is not refactored to reflect team instead of path ie: `AcmPath` still exists in the code etc. refactoring this is a bigger task for later can make new issue

### CODE REVIEW

**Comment by k4rni** [comment]
Do I need to wait a bit longer?
image

Because the AI png is not working for me

**Comment by jaasonw** [comment]
HUH DID I FORGOR TO COMMIT A THING LEME CHECK

**Comment by jaasonw** [comment]
i fix

**Comment by k4rni** [comment]
Looks good to me.

**Review by k4rni — APPROVED** [review]
@EthanThatOneKid just double check and see if all the files with "create" were changed to "design" because there's a lot

**Comment by jaasonw** [comment]
image
main instance i can find is here but none of these are even used anymore so i could just delete all

**Pull request merged**
