### PR TITLE
check for process.env.VERCEL_ANALYTICS_ID

### LINKED ISSUE #633: console displays 400 bad requests on local development environment with no vercel analytic ksy
image

### PR DESCRIPTION
**Pull request by jaasonw**
resolves 400 bad request error when local dev environment

image

### CODE REVIEW

**Comment by EthanThatOneKid** [comment]
What issue is this PR resolving?

**Comment by jaasonw** [comment]
the issue where it shows a bunch of red text in my console when i npm run dev

**Comment by EthanThatOneKid** [comment]
The analytics ID is currently injected into the build at build time in `svelte.config.js`.<https://github.com/EthanThatOneKid/acmcsuf.com/blob/6f43b291b1d362b13d879f51c39acdcbc870eadb/svelte.config.js#L9>

SvelteKit generates types for the available environment variables at build time. I think it might be possible to extend the functionality described here: <https://kit.svelte.dev/docs/modules#$env-dynamic-public>.

**Review by EthanThatOneKid — APPROVED** [review]
After some light reorganization, this PR lgtm!

**Comment by jaasonw** [comment]
oh

**Pull request merged**
